blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question
    url: https://github.com/PankajBaliyan/SnippetVerse/discussions
    about: Ask questions or get help in discussions instead of opening issues.
